import type { HrEntityKey } from '../../../shared/types/hr'
import type { HrEntityFormValues } from '../lib/hrEntityFormMapper'

export const hrEntityDefaults: Record<HrEntityKey, HrEntityFormValues> = {
  employees: {
    last_name: '',
    first_name: '',
    middle_name: '',
    department_id: '',
    position_id: '',
    birth_date: '',
    gender: '',
    phone: '',
    email: '',
    hire_date: '',
    salary: '0',
    status: 'active',
    address_country: '',
    address_city: '',
    address_street: '',
    address_house: '',
    address_apartment: '',
    address: '',
    note: '',
  },
  departments: {
    name: '',
    manager_name: '',
    phone: '',
    email: '',
    location: '',
    created_on: '',
    note: '',
  },
  positions: {
    name: '',
    base_salary: '0',
    allowance: '0',
    bonus: '0',
    responsibilities: '',
    requirements: '',
    note: '',
  },
  vacations: {
    employee_id: '',
    vacation_type: '',
    starts_at: '',
    ends_at: '',
    days_count: '0',
    reason: '',
    status: 'planned',
    note: '',
  },
  payroll: {
    employee_id: '',
    accrual_month: '',
    base_salary: '0',
    bonus: '0',
    allowance: '0',
    deductions: '0',
    taxes: '0',
    paid_at: '',
    note: '',
  },
}
