import type { HrEntityKey } from "../../../shared/types/hr";
import type { HrEntityFormValues } from "../lib/hrEntityFormMapper";

export const hrEntityDefaults: Record<HrEntityKey, HrEntityFormValues> = {
  enterprises: {
    name: "",
    legal_name: "",
    registration_number: "",
    general_director_employee_id: "",
    phone: "",
    email: "",
    address: "",
    note: "",
  },
  employees: {
    last_name: "",
    first_name: "",
    middle_name: "",
    department_id: "",
    position_id: "",
    birth_date: "",
    gender: "",
    phone: "",
    email: "",
    hire_date: "",
    salary: "0",
    status: "active",
    address_country: "",
    address_city: "",
    address_street: "",
    address_house: "",
    address_apartment: "",
    address: "",
    note: "",
  },
  employee_education: {
    employee_id: "",
    education_type: "general",
    education_degree: "secondary_general",
    institution_name: "",
    speciality: "",
    started_at: "",
    ended_at: "",
    document_number: "",
    note: "",
  },
  employee_experience: {
    employee_id: "",
    company_name: "",
    position_name: "",
    started_at: "",
    ended_at: "",
    is_current: "0",
    responsibilities: "",
    note: "",
  },
  employment_history: {
    employee_id: "",
    change_type: "position",
    previous_department_id: "",
    new_department_id: "",
    previous_position_id: "",
    new_position_id: "",
    previous_salary: "",
    new_salary: "",
    effective_at: "",
    reason: "",
    note: "",
  },
  departments: {
    enterprise_id: "",
    director_employee_id: "",
    name: "",
    manager_name: "",
    phone: "",
    email: "",
    location: "",
    created_on: "",
    note: "",
  },
  positions: {
    department_id: "",
    name: "",
    base_salary: "0",
    allowance: "0",
    bonus: "0",
    responsibilities: "",
    requirements: "",
    note: "",
  },
  vacations: {
    employee_id: "",
    vacation_type: "",
    starts_at: "",
    ends_at: "",
    days_count: "0",
    is_paid: "1",
    payment_amount: "0",
    reason: "",
    status: "planned",
    approved_at: "",
    note: "",
  },
  payroll: {
    employee_id: "",
    accrual_month: "",
    base_salary: "0",
    bonus: "0",
    allowance: "0",
    deductions: "0",
    taxes: "0",
    paid_at: "",
    note: "",
  },
};
